In [1]:
import numpy as np
import GPyOpt
import GPy
import GPyOpt.models
import GPyOpt.core

from setup import get_best_evaluation

In [2]:
def hartmann3d(x):
    x = np.atleast_2d(x)

    A = np.array([[3.0, 10.0, 30.0], [0.1,10.0,35.0], [3.0, 10.0, 30.0], [0.1, 10.0, 35.0]])
    P = np.array([[3689, 1170, 2673],[4699, 4387, 7470],[1091, 8732, 5547],[381, 5743, 8828]]) * 1e-4
    alpha = np.array([[1.0, 1.2, 3.0, 3.2]]).T
    
    expTerm = np.diagonal(-1*((x[:,np.newaxis,:] - P[np.newaxis,:,:]) ** 2)@A.T, axis1=1,axis2=2)
    
    ret = -1*(np.exp(expTerm)@alpha)
    
    return ret

mixed_domain =[{'name': 'var1', 'type': 'continuous', 'domain': (0,1)},
               {'name': 'var2', 'type': 'continuous', 'domain': (0,1)},
               {'name': 'var3', 'type': 'continuous', 'domain': (0,1)}]
space = GPyOpt.Design_space(mixed_domain)

In [3]:
acquisitions = [
    {
        'type': 'ei',
        'epsilon': 1e-2
    },
    {
        'type': 'pi',
        'epsilon': 1e-2
    },
    {
        'type': 'lcb',
        'upsilon': 0.2,
        'delta': 0.1
    },
]

factor_bernoulli_prior_parameters = {
    'alpha': 17,
    'beta': 3
}

eta_exponential_parameters = {
    'alpha': 40,
    'beta': 1/0.1
}

In [4]:
X_init = np.array([[0.5, 0.5, 0.5], [0.25, 0.25, 0.25],[0.75, 0.75, 0.75]])
y_init = hartmann3d(X_init)

In [5]:
evaluations, scores = get_best_evaluation(X_init, y_init, space, acquisitions, hartmann3d, factor_bernoulli_prior_parameters, eta_exponential_parameters, iterations=100)

In [6]:
evaluations

array([[ 0.5       ,  0.5       ,  0.5       , -0.62802202],
       [ 0.25      ,  0.25      ,  0.25      , -0.7996378 ],
       [ 0.75      ,  0.75      ,  0.75      , -1.89605115],
       [ 0.77202674,  0.76432897,  0.79263495, -2.10317891],
       [ 0.75127493,  0.88770107,  0.74535245, -1.03845879],
       [ 0.74653921,  0.77515341,  0.74863356, -1.72723987],
       [ 0.66124912,  0.58398636,  0.76378521, -2.97211036],
       [ 0.75147732,  0.75295615,  0.75217616, -1.8931086 ],
       [ 0.75240593,  0.73868981,  0.77264574, -2.16470331],
       [ 0.7507566 ,  0.75022686,  0.75387725, -1.92595407],
       [ 0.75237212,  0.75055475,  0.75311805, -1.91572139],
       [ 0.75294809,  0.75263846,  0.74993432, -1.87516513],
       [ 0.74163765,  0.74190154,  0.75213986, -1.97588649],
       [ 0.75297693,  0.75201358,  0.75165541, -1.89335926],
       [ 0.76456517,  0.76200658,  0.76703633, -1.93642368],
       [ 0.75381415,  0.74895663,  0.74985618, -1.8973368 ],
       [ 0.75323282,  0.

In [7]:
scores

[array([1.86350418, 2.24890218, 1.35612935]),
 array([2.78675971, 3.08802441, 2.36594712]),
 array([4.64644166, 4.9096379 , 3.93465756]),
 array([5.22205928, 5.75545251, 4.66458869]),
 array([6.59709957, 7.24887483, 5.94370244]),
 array([8.03825349, 8.80825409, 7.2755683 ]),
 array([8.15906271, 8.91491743, 7.40989282]),
 array([8.60485279, 9.3762858 , 7.83427948]),
 array([7.71880499, 8.57419255, 6.95924732]),
 array([7.03693142, 8.39929056, 6.51046208]),
 array([6.2887469 , 7.22082978, 5.80353259]),
 array([5.892647  , 6.58501591, 5.43121962]),
 array([5.12071904, 5.61076639, 4.71793382]),
 array([5.07736786, 5.38287691, 4.36424189]),
 array([4.87286966, 5.57688602, 4.44007091]),
 array([4.59791047, 5.61761244, 4.33421501]),
 array([4.02293562, 4.66490923, 4.05652399]),
 array([4.88024968, 4.83170622, 4.75227971]),
 array([4.10077333, 4.22851466, 4.01371739]),
 array([3.53340655, 3.84698395, 3.49798288]),
 array([4.13676847, 4.43927774, 3.94091658]),
 array([4.45882998, 4.88993346, 4.